lava-blocked: true
lava-fill-blocked: true
logging: true
water-blocked: true
water-fill-blocked: true
disallow-message: You can't use this item!
kick: true
kick-message: You have been kicked for using a blocked item!
blacklist: